labels:
  - name: Documentation
    patterns:
      - '*.md'
      - 'docs/**'

  - name: Config
    patterns:
      - '.github/**'
      - '*.config.*'

  - name: Events
    patterns:
      - 'events/**'

  - name: Commands
    patterns:
      - 'commands/**'

  - name: MessageCommand
    patterns:
      - 'commands/message*'

  - name: SlashCommand
    patterns:
      - 'commands/slash*'

  - name: UserCommand
    patterns:
      - 'commands/user*'

# Add more labels and patterns as needed.
