Documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/*', '**/*.md']
  
Config:
  - changed-files:
    - any-glob-to-any-file: ['config/*', '**/*.json', '**/*.yml', '**/*.yaml']
  
Events:
  - changed-files:
    - any-glob-to-any-file: ['events/*']
  
Commands:
  - changed-files:
    - any-glob-to-any-file: ['commands/*']

MessageCommand:
  - changed-files:
    - any-glob-to-any-file: ['commands/message*']
  
SlashCommand:
  - changed-files:
    - any-glob-to-any-file: ['commands/slash*']
  
UserCommand:
  - changed-files:
    - any-glob-to-any-file: ['commands/user*']

Core:
  - changed-files:
    - any-glob-to-any-file: ['index.js','.eslintrc.js','package.json']

Feature:
  - head-branch: ['^feat', '^feature']

Fix:
  - head-branch: ['^fix', '^bug']

Chore:
  - head-branch: ['^chore', 'chore']    
# Add more labels and patterns as needed.
