name: Code Quality Check

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  lint-and-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint
        continue-on-error: true  # Continue on linting errors, but set an environment variable

      - name: Set Lint Status
        run: echo "LINT_STATUS=$?" >> $GITHUB_ENV

      - name: Use actions/labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml  # Specify the path to your labeler configuration

      - name: Label PR
        if: success()  # Only label if linting passed
        run: echo "PR_LABELS=${{ steps.labeler.outputs.labels }}" >> $GITHUB_ENV

      - name: Determine changes
        id: changes
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"

      - name: Display labels
        run: echo "PR labels: ${{ env.PR_LABELS }}"
