name: Apply Labels

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Use actions/labeler
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          dot: true
