name: Lint Code

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set Up Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        id: lint
        run: npm run lint
        # Replace with your linting command, e.g., "npm run eslint" or "eslint ."

      - name: Add Label on Success
        if: steps.lint.outcome == 'success'
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/labels"
          curl -X POST -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" -d '{"labels":["Linted"]}' "$URL"
